FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy the built application from local build/ folder
# This folder is generated by running 'npm run build' locally
COPY build/ ./

# Install production dependencies only
RUN npm ci --omit=dev

# Copy startup script
COPY start.sh ./start.sh
RUN chmod +x ./start.sh

# Environment variables
ENV NODE_ENV=production
ENV PORT=80
ENV HOST=0.0.0.0

# Expose port (CapRover standard)
EXPOSE 80

# Start the application (runs migrations then starts server)
CMD ["./start.sh"]
